# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eb5224e78ce99a0ecf7ec662e89734874f67d5674ff8e399b2f3136aac53047f3fdbb4ea2c742cfd80fe99ec919288a496dcd3629b2146da08912be875f4b758

test:
  secret_key_base: 1a07c84dde8abda490b590a00435c786ffa0c6216ddcaa38b8ba4951bb712013221e58e097971988f732623de160284e4858c671834c443fdbea32556a023bf7

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
